# Blueprint Render — SmartTransport API
services:
  - type: web
    name: smart-transport-api
    runtime: docker
    dockerfilePath: ./Dockerfile.production
    region: frankfurt
    plan: free
    healthCheckPath: /up
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: SmartTransport
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: <ton-host.aivencloud.com>
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        value: smart_transport
      - key: DB_USERNAME
        value: <ton_user>
      - key: DB_PASSWORD
        value: <ton_password>
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: SEED_DATABASE
        value: "true"
